from setuptools import setup, find_packages

setup(
    name="transformers-main",
    version="0.1.0",
    description="A comprehensive PyTorch-based project for fine-tuning transformer models",
    author="AI Developer",
    author_email="developer@example.com",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.21.0",
        "datasets>=2.0.0",
        "tokenizers>=0.13.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "tqdm>=4.62.0",
        "wandb>=0.12.0",
        "tensorboard>=2.8.0",
        "accelerate>=0.20.0",
        "evaluate>=0.4.0",
        "peft>=0.4.0",
        "bitsandbytes>=0.41.0",
        "deepspeed>=0.9.0",
        "optuna>=3.0.0",
        "hydra-core>=1.2.0",
        "omegaconf>=2.2.0",
        "rich>=12.0.0",
        "click>=8.0.0",
        "PyYAML>=6.0",
        "scipy>=1.7.0",
        "sentencepiece>=0.1.97",
        "protobuf>=3.20.0",
        "psutil>=5.8.0",
        "gputil>=1.4.0"
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)